//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        public Class()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public string Group { get; set; }
        public int SchoolId { get; set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
