//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schools
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.Class = new HashSet<Class>();
            this.Student = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public string FullName { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Class> Class { get; set; }
        public virtual ICollection<Student> Student { get; set; }
    }
}
